# Generated by Django 3.2.3 on 2021-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210529_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='fasdf', max_length=255),
            preserve_default=False,
        ),
    ]
